# Generated by Django 3.1 on 2021-09-02 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='short_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.project'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
